org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mc_version=1.20.1
forge_version=47.3.0
mappings_channel=official
mappings_version=1.20.1
jei_version=15.20.0.130
gtm_version=7.5.3
ldlib_version=1.0.40.b
create_version=6.0.8-291

mod_id=recipe_data_exporter
mod_name=Recipe Data Exporter
mod_version=0.1.0
mod_group_id=dev.alperovi.recipedataexporter
